// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drrugowjfdfymamcaovd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycnVnb3dqZmRmeW1hbWNhb3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTQwMjMsImV4cCI6MjA2ODE3MDAyM30.8GgyMDRx_aCjxtbRUOANaZcBGW2adeJcfqSflTK49-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});